name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish-repo:
    name: Publish repository
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Publish repository
        uses: ./publish-repo
        with:
          sync-tags: v1
          sync-token: ${{ secrets.TANAAB_COAXIUM_INJECTOR }}
